# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iiwHtR3W-rbkvW58BaDR-iU4vQ3CuPRf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
def linear_regression(x, y):
    xy = x * y
    x_squared = x ** 2
    y_squared = y ** 2
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    b = np.sum((x - mean_x) * (y - mean_y)) / np.sum((x - mean_x) ** 2)
    a = mean_y - b * mean_x
    si = (y - a - b * x) ** 2
    S = np.sum(si)
    return a, b, S
def exponential_regression(x, y):
    X = np.log(x)
    Y = np.log(y)
    XY = X * Y
    X_squared = X ** 2
    Y_squared = Y ** 2
    mean_X = np.mean(X)
    mean_Y = np.mean(Y)
    b = np.sum((X - mean_X) * (Y - mean_Y)) / np.sum((X - mean_X) ** 2)
    A = mean_Y - b * mean_X
    a = np.exp(A)
    si = (Y - A - b * X) ** 2
    S = np.sum(si)
    return a, b, A, S
def main():
    print("Pilih jenis regresi:")
    print("1. Regresi Linier y = a + bx")
    print("2. Regresi Linier y = ax^b")
    print("3. Regresi Eksponensial y = ae^-bx")
    choice = int(input("Masukkan nomor jenis regresi yang ingin digunakan: "))
    data_input_x = input("Masukkan nilai x (dipisahkan dengan spasi): ")
    data_input_y = input("Masukkan nilai y (dipisahkan dengan spasi): ")
    x = np.array([float(val) for val in data_input_x.split()])
    y = np.array([float(val) for val in data_input_y.split()])
    n = len(x)
    if choice == 1:
        a, b, S = linear_regression(x, y)
        formula = f"y = {a} + {b}x"
        A = None
    elif choice == 2:
        a, b, A, S = exponential_regression(x, y)
        formula = f"ln(f(x)) = {A} + {b}x"
    elif choice == 3:
        a, b, S = linear_regression(x, np.log(y))
        formula = f"ln(y(t)) = {a} - ({b})t"
        A = None
    else:
        print("Pilihan tidak valid.")
        return
    #printtable
    data = {'x': x, 'y': y, 'X': np.log(x), 'Y': np.log(y), 'X^2': (np.log(x))**2, 'Y^2': (np.log(y))**2}
    df = pd.DataFrame(data)
    print("\nTabel:")
    print(df)
    print("Nilai a:", a)
    if A is not None:
        print("Nilai A:", A)
    print("Nilai b:", b)
    print("Nilai S:", S)
   #printgraphic
    plt.scatter(x, y, label="Data Titik")
    if choice == 1:
        regression_line = a + b * x
    elif choice == 2:
        regression_line = a * x**b
    elif choice == 3:
        regression_line = np.exp(a + b * x)
    plt.plot(x, regression_line, color='red', label="Hasil Regresi")
    plt.xlabel("Nilai x")
    plt.ylabel("Nilai y")
    plt.title("Regresi dan Data Titik")
    plt.legend()
    plt.grid(True)
    plt.show()
    print(f"Soal nomor {choice} memiliki Regresi  {formula} ")
if __name__ == "__main__":
    main()

import numpy as np
import pandas as pd
#data
t = np.array([0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5])
y = np.array([1.000, 0.994, 0.990, 0.985, 0.979, 0.977, 0.972, 0.969, 0.967, 0.960, 0.956, 0.952])
#penyesuaiandata
Y = np.log(y)
#perhitungankolom
tY = t * Y
t_squared = t ** 2
Y_squared = Y ** 2
#penghitungannilaiab
mean_t = np.mean(t)
mean_Y = np.mean(Y)
b = np.sum((t - mean_t) * (Y - mean_Y)) / np.sum((t - mean_t) ** 2)
A = mean_Y - b * mean_t
a = np.exp(A)
si = (Y - A + b * t) ** 2
#dataframe
data = {'No.': range(1, len(t) + 1), 't': t, 'y': y, 'ln(y)': Y, 't*ln(y)': tY, 't^2': t_squared, '(ln(y))^2': Y_squared, 's_i': si}
df = pd.DataFrame(data)
#countS
S = np.sum(si)
#counttandty
jumt = np.sum(t)
jumty = np.sum(tY)
#printdataframe
print(df)
#printabs
print("\nNilai a:", a)
print("\nNilai A:", A)
print("\nNilai b:", b)
print("\nNilai S:", S)
print("\nJumlah t:", jumt)
print("\nJumlah tY:", jumty)
print("\nBentuk Persamaan Regresi Liniernya adalah: ln(y(t)) = ",A,"- (",b,")t" )

import numpy as np
import pandas as pd
#data
x = np.array([0.5, 1.0, 1.5, 2.0, 2.5])
y = np.array([0.49, 1.60, 3.36, 6.44, 10.16])
#penyesuaiandata
X = np.log(x)
Y = np.log(y)
#perhitungankolom
XY = X * Y
X_squared = X ** 2
Y_squared = Y ** 2
#countab
mean_X = np.mean(X)
mean_Y = np.mean(Y)
b = np.sum((X - mean_X) * (Y - mean_Y)) / np.sum((X - mean_X) ** 2)
A = mean_Y - b * mean_X
a = np.exp(A)
si = (Y - A - b * X) ** 2
#builddataframe
data = {'No.': range(1, len(x) + 1), 'x': x, 'y': y, 'ln(x)': X, 'ln(y)': Y, 'ln(x)*ln(y)': XY, '(ln(x))^2': X_squared, '(ln(y))^2': Y_squared, 's_i': si}
df = pd.DataFrame(data)
#counts
S = np.sum(si)
#countxandxy
jumx = np.sum(X)
jumxy = np.sum(XY)
#printdataframe
print(df)
#printabs
print("\nNilai a:", a)
print("\nNilai A:", A)
print("\nNilai b:", b)
print("\nNilai S:", S)
print("\nJumlah X:", jumx)
print("\nJumlah XY:", jumxy)
print("\nBentuk Persamaan Regresi Liniernya adalah: ln(f(x)) = ",A,"+",b,"ln(x)" )